Ci sono alcuni fattori che influenzano gli eventi di morte. Questo dataset contiene informazioni sulla persona: età, sesso, pressione sanguigna, fumo. Dobbiamo prevedere il loro EVENTO DI MORTE. Questo dataset è molto piccolo, quindi è meglio non trattare questi dati in modo così serio.

# Importazione di librerie

In [ ]:
import warnings
import pandas as pd
import numpy as np
import seaborn as sns
#from colorama import Fore, Back, Style
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from mlxtend.plotting import plot_confusion_matrix
from plotly.offline import plot, iplot, init_notebook_mode
import plotly.graph_objs as go
from plotly.subplots import make_subplots
import plotly.express as px
from statsmodels.formula.api import ols
import plotly.graph_objs as gobj

init_notebook_mode(connected=True)
warnings.filterwarnings('ignore')


%matplotlib inline

import xgboost
import lightgbm
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
#from catboost import CatBoostClassifier

# Esplorazione dei dati

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving heart_failure_clinical_records_dataset.csv to heart_failure_clinical_records_dataset (3).csv


In [ ]:
import io
dataset = pd.read_csv(io.StringIO(uploaded['heart_failure_clinical_records_dataset.csv'].decode('utf-8')))
dataset.head()

age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
0  75.0        0                       582  ...        0     4            1
1  55.0        0                      7861  ...        0     6            1
2  65.0        0                       146  ...        1     7            1
3  50.0        1                       111  ...        0     7            1
4  65.0        1                       160  ...        0     8            1

[5 rows x 13 columns]

In [ ]:
dataset['DEATH_EVENT'].value_counts()

0    203
1     96
Name: DEATH_EVENT, dtype: int64

* Sesso - Sesso del paziente value_counts1, Femmina - 0
* Età - Età del paziente
* Diabete - 0 = No, 1 = Sì
* Anemia - 0 = No, 1 = Sì
* Alta_Pressione_Sangue - 0 = No, 1 = Sì
* Fumare - 0 = No, 1 = Sì
* MORTE_EVENTO - 0 = No, 1 = Sì

In [ ]:
dataset.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [ ]:
dataset.describe()

age     anaemia  ...        time  DEATH_EVENT
count  299.000000  299.000000  ...  299.000000    299.00000
mean    60.833893    0.431438  ...  130.260870      0.32107
std     11.894809    0.496107  ...   77.614208      0.46767
min     40.000000    0.000000  ...    4.000000      0.00000
25%     51.000000    0.000000  ...   73.000000      0.00000
50%     60.000000    0.000000  ...  115.000000      0.00000
75%     70.000000    1.000000  ...  203.000000      1.00000
max     95.000000    1.000000  ...  285.000000      1.00000

[8 rows x 13 columns]

In [ ]:
X=dataset.drop('DEATH_EVENT',axis=1) #trainset
y=dataset['DEATH_EVENT'] #testset
X.head()

age  anaemia  creatinine_phosphokinase  ...  sex  smoking  time
0  75.0        0                       582  ...    1        0     4
1  55.0        0                      7861  ...    1        0     6
2  65.0        0                       146  ...    1        1     7
3  50.0        1                       111  ...    1        0     7
4  65.0        1                       160  ...    0        0     8

[5 rows x 12 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
X_train, X_validation, y_train, y_validation = train_test_split(X_train, y_train, test_size=0.1, random_state=1)

## Rete neurale

In [ ]:
from tensorflow.python.keras import Sequential
classifier = Sequential()

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
X_validation=pca.transform(X_validation)

In [ ]:
from tensorflow.python.keras.layers import Dense
classifier.add(Dense(6, kernel_initializer='uniform', activation= 'relu'))
classifier.add(Dense(5, kernel_initializer='uniform', activation= 'relu'))
classifier.add(Dense(3, kernel_initializer='uniform', activation= 'relu'))
classifier.add(Dense(1, kernel_initializer='uniform', activation= 'sigmoid'))
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])


In [ ]:
from keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=5)
c=classifier.fit(X_train,y_train,batch_size=10,epochs=500, validation_data=(X_validation, y_validation), callbacks=[es])


Epoch 1/500
22/22 [==============================] - 1s 9ms/step - loss: 0.6828 - accuracy: 0.6651 - val_loss: 0.6638 - val_accuracy: 0.7083
Epoch 2/500
22/22 [==============================] - 0s 2ms/step - loss: 0.6832 - accuracy: 0.6651 - val_loss: 0.6498 - val_accuracy: 0.7083
Epoch 3/500
22/22 [==============================] - 0s 2ms/step - loss: 0.6756 - accuracy: 0.6651 - val_loss: 0.6510 - val_accuracy: 0.7083
Epoch 4/500
22/22 [==============================] - 0s 2ms/step - loss: 0.6756 - accuracy: 0.6651 - val_loss: 0.6511 - val_accuracy: 0.7083
Epoch 5/500
22/22 [==============================] - 0s 2ms/step - loss: 0.6743 - accuracy: 0.6651 - val_loss: 0.6512 - val_accuracy: 0.7083
Epoch 6/500
22/22 [==============================] - 0s 2ms/step - loss: 0.6722 - accuracy: 0.6651 - val_loss: 0.6411 - val_accuracy: 0.7083
Epoch 7/500
22/22 [==============================] - 0s 2ms/step - loss: 0.6706 - accuracy: 0.6651 - val_loss: 0.6446 - val_accuracy: 0.7083
Epoch 8/500
2

In [ ]:
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test, y_pred))

[[43  0]
 [17  0]]


In [ ]:
def print_score(classifier,X_train,y_train,X_test,y_test,train=True):
    if train == True:
        print("Training results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_train,classifier.predict(X_train))))
        print('Classification Report:\n{}\n'.format(classification_report(y_train,classifier.predict(X_train))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_train,classifier.predict(X_train))))
        res = cross_val_score(classifier, X_train, y_train, cv=10, n_jobs=-1, scoring='accuracy')
        print('Average Accuracy:\t{0:.4f}\n'.format(res.mean()))
        print('Standard Deviation:\t{0:.4f}'.format(res.std()))
    elif train == False:
        print("Test results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_test,classifier.predict(X_test))))
        print('Classification Report:\n{}\n'.format(classification_report(y_test,classifier.predict(X_test))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_test,classifier.predict(X_test))))

In [ ]:
 print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.72      1.00      0.83        43
           1       0.00      0.00      0.00        17

    accuracy                           0.72        60
   macro avg       0.36      0.50      0.42        60
weighted avg       0.51      0.72      0.60        60



## Regressore Logistico

In [ ]:
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [ ]:
print_score(classifier,X_train,y_train,X_test,y_test,train=True)

Training results:

Accuracy Score: 0.5488

Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.55      0.62       143
           1       0.38      0.56      0.45        72

    accuracy                           0.55       215
   macro avg       0.55      0.55      0.53       215
weighted avg       0.60      0.55      0.56       215


Confusion Matrix:
[[78 65]
 [32 40]]

Average Accuracy:	0.5115

Standard Deviation:	0.1031


In [ ]:
print_score(classifier,X_train,y_train,X_test,y_test,train=False)

Test results:

Accuracy Score: 0.4833

Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.47      0.56        43
           1       0.28      0.53      0.37        17

    accuracy                           0.48        60
   macro avg       0.50      0.50      0.47        60
weighted avg       0.59      0.48      0.51        60


Confusion Matrix:
[[20 23]
 [ 8  9]]



## SVM

In [ ]:
#from sklearn.svm import SVC
classifier = SVC(kernel='rbf',random_state=42) #differenza con poly e altri kernel

classifier.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=42, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
print_score(classifier,X_train,y_train,X_test,y_test,train=True)

Training results:

Accuracy Score: 0.6651

Classification Report:
              precision    recall  f1-score   support

           0       0.67      1.00      0.80       143
           1       0.00      0.00      0.00        72

    accuracy                           0.67       215
   macro avg       0.33      0.50      0.40       215
weighted avg       0.44      0.67      0.53       215


Confusion Matrix:
[[143   0]
 [ 72   0]]

Average Accuracy:	0.6604

Standard Deviation:	0.0210


In [ ]:
print_score(classifier,X_train,y_train,X_test,y_test,train=False)

Test results:

Accuracy Score: 0.7167

Classification Report:
              precision    recall  f1-score   support

           0       0.72      1.00      0.83        43
           1       0.00      0.00      0.00        17

    accuracy                           0.72        60
   macro avg       0.36      0.50      0.42        60
weighted avg       0.51      0.72      0.60        60


Confusion Matrix:
[[43  0]
 [17  0]]



In [ ]:
classifier = SVC(kernel='linear',random_state=42)

classifier.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=42, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
print_score(classifier,X_train,y_train,X_test,y_test,train=True)


Training results:

Accuracy Score: 0.6651

Classification Report:
              precision    recall  f1-score   support

           0       0.67      1.00      0.80       143
           1       0.00      0.00      0.00        72

    accuracy                           0.67       215
   macro avg       0.33      0.50      0.40       215
weighted avg       0.44      0.67      0.53       215


Confusion Matrix:
[[143   0]
 [ 72   0]]

Average Accuracy:	0.6368

Standard Deviation:	0.0483


In [ ]:
print_score(classifier,X_train,y_train,X_test,y_test,train=False)

Test results:

Accuracy Score: 0.7000

Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.98      0.82        43
           1       0.00      0.00      0.00        17

    accuracy                           0.70        60
   macro avg       0.36      0.49      0.41        60
weighted avg       0.51      0.70      0.59        60


Confusion Matrix:
[[42  1]
 [17  0]]



##K-Neighbours Classifier

In [ ]:
# K Neighbours Classifier
kn_clf = KNeighborsClassifier(n_neighbors=6)
kn_clf.fit(X_train,y_train)
kn_pred = kn_clf.predict(X_test)
kn_acc = accuracy_score(y_test,kn_pred)
print(kn_acc * 100)

70.0


In [ ]:
print('Accuracy of KNeighbours is : ', '{:.2f}%'.format(100 * kn_acc))

Accuracy of KNeighbours is :  70.00%
